name = "hecke-landau"
version = "0.1.0"
keywords = ["math", "number-theory"]
defaultTargets = ["HeckeLandau"]

[leanOptions]
pp.unicode.fun = true
relaxedAutoImplicit = false

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "676b870c7dd6f238"

[[lean_lib]]
name = "HeckeLandau"
